# Economic Data API Specifications
# INTEREST RATES //
# IMF ONLY SUPPORTS MONTHLY.
# ECB ONLY SUPPORTS MONTHLY.

# CPI //
# IMF SUPPORTS ANNUAL, MONTHLY, QUARTERLY.
# ECB ONLY SUPPORTS MONTHLY.

# UNEMPLOYMENT //
# IMF SUPPORTS ANNUAL, MONTHLY, QUARTERLY.
# ECB ONLY SUPPORTS QUARTERLY.

# GDP //
# IMF SUPPORTS YEARLY, QUARTERLY.
# ECB ONLY SUPPORTS QUARTERLY.

# BOP //
# IMF SUPPORTS YEARLY, QUARTERLY

BASE_URL = "http://192.168.1.212:8000"
